apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: <dockerimage>
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5000
  
